module.exports = {
  purge: {    
    content: [
      'src/**/*.js',
      'src/**/*.jsx',
      'src/**/*.ts',
      'src/**/*.tsx',
      'public/**/*.html',
    ],
    options: {
      safelist: [
        'w-1/12',
        'w-2/12',
        'w-3/12',
        'w-4/12',
        'w-5/12',
        'w-6/12',
        'w-7/12',
        'w-8/12',
        'w-9/12',
        'w-10/12',
        'w-11/12',
        'w-12/12',

        'sm:w-1/12',
        'sm:w-2/12',
        'sm:w-3/12',
        'sm:w-4/12',
        'sm:w-5/12',
        'sm:w-6/12',
        'sm:w-7/12',
        'sm:w-8/12',
        'sm:w-9/12',
        'sm:w-10/12',
        'sm:w-11/12',
        'sm:w-12/12',

        'lg:w-1/12',
        'lg:w-2/12',
        'lg:w-3/12',
        'lg:w-4/12',
        'lg:w-5/12',
        'lg:w-6/12',
        'lg:w-7/12',
        'lg:w-8/12',
        'lg:w-9/12',
        'lg:w-10/12',
        'lg:w-11/12',
        'lg:w-12/12',

        'font-100',
        'font-200',
        'font-300',
        'font-400',
        'font-500',
        'font-600',
        'font-700',
        'font-100',

        'font-thin',
        'font-extralight',
        'font-light',
        'font-normal',
        'font-medium',
        'font-semibold',
        'font-bold',
        'font-extrabold',
        'font-black',
      ],
    },
  },
  theme: {
    fontFamily: {
      'sans': ['Noto Sans JP', 'ui-sans-serif', 'system-ui'],
    },
    extend: {
      spacing: {
        '50p': "50%",
        '100p': "100%",
      }
    },
  },
  variants: {},
  plugins: [],
}